name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build-android-web:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - run: flutter --version
      - name: Running flutter pub
        run: flutter pub get
      - name: Running flutter test
        run: flutter test
      - name: Clean build
        run: flutter clean
      - name: Building for android apk & appbundle
        run: |
          flutter build apk
          flutter build appbundle
  build-ios:
    name: Build ios
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - name: Running flutter pub
        run: flutter pub get
      - name: Running flutter test
        run: flutter test
      - name: Clean build
        run: flutter clean
      - name: Building for ios
        run: flutter build ios --release --no-codesign
